id: P010598
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30514
  title: རྗེ་སྒོ་བློ་གསུམ་གྱི་དྲང་ངེས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c8516531694242a39b2e14d577e1c86c:
      image_group_id: I1PD96328
      title: ''
      volume_number: 1
      total_pages: 664
      base_file: v001.txt
