id: I430C4C20
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:48:13+00:00'
last_modified: '2022-06-08T16:08:32.069281+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30514
  title: རྗེ་སྒོ་བློ་གསུམ་གྱི་དྲང་ངེས་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D74D:
      image_group_id: I1PD96328
      title: ''
      total_pages: 664
      order: 1
      base_file: D74D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
